-- Create Messages table for chat
create table public.messages (
  id bigint generated by default as identity primary key,
  sender_id text not null references public.profiles(id),
  receiver_id text not null references public.profiles(id),
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for messages
alter table public.messages enable row level security;

-- Policy: Users can read messages where they are sender or receiver
create policy "Users can read own messages" 
on public.messages for select 
using (auth.uid()::text = sender_id or auth.uid()::text = receiver_id);

-- Policy: Users can insert messages if they are authenticated (In prod, check match status)
create policy "Users can send messages" 
on public.messages for insert 
with check (auth.uid()::text = sender_id);

-- Update Swipes policy to allow users to see who liked them (for 'Likes You' feature)
-- Current policy was "allow all", checking to be safe.
-- If we want to be strict: 
-- drop policy "Allow all actions for authenticated users" on public.swipes;
-- create policy "Users can see their own swipes" on public.swipes for select using (swiper_id = auth.uid()::text);
-- create policy "Users can see swipes ON them" on public.swipes for select using (target_id = auth.uid()::text);
-- For now, existing policy allows reading all swipes, so it works.
