-- Enable PostGIS extension for location search
create extension if not exists postgis;

-- Create Profiles table
create table public.profiles (
  id text not null primary key, -- Set this to Clerk User ID
  name text not null,
  age integer,
  bio text,
  images text[],
  location geography(Point, 4326),
  last_active timestamp with time zone default timezone('utc'::text, now()),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (Row Level Security)
alter table public.profiles enable row level security;

-- Policy (Simple version for initial dev): Allow all authenticated (with valid JWT) to read/write
-- In production, you should restrict write access to the owner (id = current_user_id via JWT)
create policy "Allow all actions for authenticated users" 
on public.profiles
for all 
using (true) 
with check (true);

-- Create Swipes table
create table public.swipes (
  id bigint generated by default as identity primary key,
  swiper_id text not null references public.profiles(id),
  target_id text not null references public.profiles(id),
  direction text not null check (direction in ('left', 'right', 'up')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(swiper_id, target_id)
);

alter table public.swipes enable row level security;
create policy "Allow all actions for authenticated users" on public.swipes for all using (true);

-- Create Matches view (Bidirectional 'right' or 'up' swipe)
create or replace view public.matches as
select
  s1.swiper_id as user_id_1,
  s1.target_id as user_id_2,
  least(s1.created_at, s2.created_at) as matched_at
from public.swipes s1
join public.swipes s2 on s1.target_id = s2.swiper_id and s1.swiper_id = s2.target_id
where (s1.direction = 'right' or s1.direction = 'up') 
  and (s2.direction = 'right' or s2.direction = 'up');
